export const selectors = {
    url:"https://app.pws.int.cruk.org/support-us/your-donation",
    donationDetails: {
        acceptCookies:"onetrust-accept-btn-handler",
        logo:"Cancer Research UK logo",
        pageTitle:"Together we will beat cancer",
        titleText: "Donation amount",
        titlePath: "(//h2[@class='sc-ftvSup ZgqnA'])[1]",
        amountLabelText: "Please choose an amount for your  donation. (required)",
        amountLabelPath: "amountRadioGroupLabel",
        selectAmount:(val:string)=> `amount${val}`,
        pymtOptionLink:"sc-eCYdqJ.kBYtqB.sc-gKXOVf.fGaNDd",
        oneOffLinkText:"Make a one-off donation instead",
        regularLinkText:"Make a regular donation instead",
        otherAmount: "amountCurrency",
        amtErrorText: "Please select or type in the amount you'd like to donate.",
        amtErrorPath:"donationAmount-error",
        frequencyLabelTxt: "Tell us how often you’d like to donate (required)",
        frequencyLabelPath: "frequencyLabel",
        selectFrequency: "frequency-Monthly", 
        frequencyErrorText:"Please select how often you'd like to make your donation.",
        frequencyErrorPath: "donationFrequency-error",
        frequency: "frequency",
        motivationContent:"We may use this information to tailor messages, or to send you information which may be helpful to you. We will keep this information confidential, but you do not need to provide a response if you’re not comfortable.",
        addressContent:"We use your address information to check if you’ve supported Cancer Research UK before. This will help us make sure that our records are up to date so we can send you relevant information.",
        postcodeText:"Please enter a valid UK postcode to find address",
        discli1: "We can only claim Gift Aid on donations of your own money.",
        discli2:"Your donation is not eligible for Gift Aid if you received anything in return for it or raised it from your own fundraising.",
        otherAmountID:"otherAmount",
        donationTypeText:"Donation type",
        donationTypeLabel:"Please choose your donation type. (required)",
        donationTypeOptn:"I am donating my own money",
        motivationText:"Your motivation",
        reasonLabel:"Would you like to tell us why you’re making a donation?",
        discLink :"Why are we asking this?",
        memoryID :"inMemoryName",
        donationGoesText:"Where your donation goes",
        donationGoesLabel:"Choose how you would like your donation to fund our work.",
        cancerTypeTxt:"Choose a cancer type or an area of research",
        donationTypeRadio1:"I am donating my own money",
        donationTypeRadio2:"I am paying in money from fundraising or a collection",
        cancerTypeRadio1:"Where the need is greatest",
        motivationType:"//select[@data-testid='selectMotivation']",
        donationTypeError:"Please select an option to continue."
    },
    personalDetails:{
        yourDetailsText:"Your details",
        titlePath:"//select[@data-testid='title']",
        firstNameText:"First name",
        firstNameID:"forename",
        lastNameText:"Last name",
        lastNameID :"surname",
        emailText:"Email address",
        emailID:"emailAddress",
        title:"Title",
        phoneOptn:"//label[input[@name='phoneOptIn']]//span[@class='sc-dmRaPn gqLghz']",
        yourAdressText:"Your address",
        addressheader:"addressCollapse-header",
        addressHeaderText:"Why are we asking this?",
        postCodeText:"Postcode",
        postcodeLabelText:"Please enter a valid UK postcode to find address",
        manualAddressText:"To enter address manually or to enter an address outside the UK, use the link below",
        manualAddressLink:"Enter address manually",
        postalCodeText :"postalCode",
        findAddress: "Find address",
        selectAddress:"Select address",
        addressOptn:"//select[@id='addressSelection']",
        address1:"input[name='addressLine1']",
        city:"input[name='city']",
        country:"#country option:checked",
        stayText:"Staying in touch with us",
        helpText:"Help us bring forward the day when all cancers are cured. Hear about our latest breakthroughs, campaigns and how you can support our life saving work.",
        contact:"We may contact you by post or phone unless you select ‘No’ below.",
        email:"Email",
        emailOptn1:"(//span[@class='sc-dmRaPn gqLghz'])[2]",
        emailOptn2:"(//span[@class='sc-dmRaPn gqLghz'])[1]",
        text:"Text",
        post:"Post",
        phone:"Phone",
        phoneNumber:"Phone number",
        phNumberID:"phoneNumber",
        firstNameError:"Please enter your first name.",
        lastNameError:"Please enter your last name.",
        emailError:"Please enter a valid email address.",
        postcodeerror:"Please enter a valid postcode.",
        phonenumberError:'Phone number is required because staying in touch by phone or text message is set to "Yes".',
        addressError:"Please select an address."
    },
    paymentDetails:{
        paymentCardID:"(//div[@class='sc-bBrHrO dyrTdO'])[1]",
        donationAmountTxt:"Donation amount",
        donationMethodLblTxt:"How would you like to donate?",
        cardText:"Credit/Debit card",
        cardFrameID:"#braintree-hosted-field-number",
        cardNumberID:"#credit-card-number",
        cardholderID:"cardholderName",
        dateFrameID:"#braintree-hosted-field-expirationDate",
        dateID:"#expiration",
        cvvFrameID:"#braintree-hosted-field-cvv",
        cvvID:"#cvv",
        giftAid:"giftAid1",
        completeDonationButton:"Complete my donation",
        loadingText:"Payment processingPlease do not refresh your browser",
        paymentMethodError:"Please select a payment method to continue.",
        cardNumberError:"Please enter the number on the front of your card.",
        cardNameError:"Please enter the name of the cardholder as it appears on the card.",
        dateError:"Please enter a valid expiry date.",
        cvvError:"Please enter a valid security code."
    },
    thankYouDetails:{
        thankYouText:"Thank you, Tester!",
        memoryText:"Giving in memory of a loved one is a special way to honour their life.",
        referenceText:"Your reference number is",
        yourDation:"Your donation",
        eyeIcon:"bullseye-icon",
        memoryLabel:"In memory of someone",
        memoryicon:"in-memory-icon",
        tqMemoryText:"In memory"
    }
}